version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        MYSQL_DATABASE: "gestionski"
        MYSQL_ROOT_HOST: "%"
    healthcheck:
        test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
        timeout: 20s
        retries: 10
    restart: always
    ulimits:
      nofile:
          soft: 65536
          hard: 65536


  spring-app:
    image: ahlemsa/gestionski
    ports:
      - "8089:8089"
    links:
        - "mysql"

    depends_on:
        - mysql

    restart: always
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - spring.datasource.url=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
