version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
       - MYSQL_ROOT_PASSWORD=
       -  MYSQL_DATABASE=gestionski

    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  spring-app:
    image: ahlemsa/gestionski
    ports:
      - "8089:8089"
    depends_on:
        - mysql
    restart: on-failure
    environment:
        SPRING_APPLICATION_JSON: '{
         "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true",
         "spring.datasource.username" : "root",
         "spring.datasource.password" : "null",
         "spring.jpa.hibernate.ddl-auto" : "update",
         "spring.jpa.properties.hibernate.dialect" :"org.hibernate.dialect.MySQL5InnoDBDialect"
        }'
    stdin_open: true
    tty: true
volumes:
  db: