version: '3.7'

services:
  # Spring Boot app container
  spring-app:
    image: anistounekti/tounektiapp:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACKEND_IMAGE_NAME=anistounekti/tounektiapp:v1
    ports:
      - "8083:8000"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/stationSki
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: R2#s7P@9q
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL5Dialect"

  # MySQL database container
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: anis
      MYSQL_DATABASE: stationSki
      MYSQL_USER: springuser
      MYSQL_PASSWORD: R2#s7P@9q