version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: stationSki
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d


  spring-application:
    image: emnaayachi/course
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
     SPRING_APPLICATION_JSON : '{
      "spring.datasource.url" : "jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : null,
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
    }'

volumes:
  mysql_data:
  mysql_config:
networks:
  app-network:
    driver: bridge